#!/usr/bin/env python3
"""
Master Brand Visual Identity System Generator (generate_vi_system.py)
---------------------------------------------------------------------
Single-Logo Input -> Full-Spectrum Brand VI Generation Pipeline:
1. Visual DNA Extraction & Tokenization (brand_tokens.json)
2. Web & Digital Tokens (tokens.css)
3. App Icon Matrix (iOS, Android, Favicon SVGs)
4. Physical Stationery & Signage (Business Card, Badge, Frosted Film, Rollup SVGs)
5. Photorealistic 3D Spatial Prompts (JSON & Markdown for Midjourney / FLUX / SD)
6. Publication-grade Interactive VI Brand Guidelines Manual (brand_guidelines.html)
"""

import os
import sys
import json
import shutil

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8')

from extract_logo_dna import build_brand_tokens
from stationery_generator import generate_all_stationery
from app_icon_generator import generate_all_icons

def generate_css_tokens(tokens, output_path):
    p = tokens["color_palette"]["primary"]
    s = tokens["color_palette"]["secondary"]
    acc = tokens["color_palette"]["accent_cta"]
    light = tokens["color_palette"]["canvas_light"]
    dark = tokens["color_palette"]["surface_dark"]
    sem = tokens["color_palette"]["semantics"]

    css = f"""/* ==========================================================================
   Brand Visual Identity Design Tokens - {tokens['brand_meta']['name']}
   Generated by Brand Visual System Master (Standard W3C Tokens)
   ========================================================================== */

:root {{
  /* Brand Core Palette */
  --brand-primary: {p['hex']};
  --brand-primary-rgb: {p['rgb'].replace('rgb', '').replace('(', '').replace(')', '')};
  --brand-secondary: {s['hex']};
  --brand-secondary-rgb: {s['rgb'].replace('rgb', '').replace('(', '').replace(')', '')};
  --brand-accent: {acc['hex']};
  --brand-accent-rgb: {acc['rgb'].replace('rgb', '').replace('(', '').replace(')', '')};

  /* Surfaces & Canvases */
  --surface-canvas: {light['hex']};
  --surface-card: #FFFFFF;
  --surface-border: #E2E8F0;
  --surface-dark: {dark['hex']};

  /* Typography Colors */
  --text-primary: #0F172A;
  --text-secondary: #475569;
  --text-muted: #94A3B8;
  --text-inverted: #FFFFFF;

  /* Semantics */
  --color-success: {sem['success']['hex']};
  --color-warning: {sem['warning']['hex']};
  --color-danger: {sem['danger']['hex']};
  --color-info: {sem['info']['hex']};

  /* Spatial & Elevation */
  --logo-clear-space: {tokens['spatial_clearance']['safe_zone']};
  --radius-sm: 6px;
  --radius-md: 12px;
  --radius-lg: 20px;
  --radius-full: 9999px;
  --shadow-sm: 0 1px 3px rgba(0,0,0,0.06);
  --shadow-md: 0 8px 20px -4px rgba(15,23,42,0.08);
  --shadow-glow: 0 0 24px -4px rgba({p['rgb'].replace('rgb', '').replace('(', '').replace(')', '')}, 0.35);

  /* Font Families */
  --font-display: {tokens['typography_pairings']['western_display']};
  --font-body: {tokens['typography_pairings']['western_body']};
  --font-chinese: {tokens['typography_pairings']['chinese_display']};
  --font-mono: {tokens['typography_pairings']['monospace_code']};
}}

/* Dark Mode Token Overrides */
[data-theme="dark"] {{
  --surface-canvas: #090D16;
  --surface-card: #0F172A;
  --surface-border: #1E293B;
  --text-primary: #F8FAFC;
  --text-secondary: #94A3B8;
  --text-muted: #64748B;
  --text-inverted: #0F172A;
}}
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(css)

def generate_photorealistic_prompts(tokens, output_json, output_md):
    name = tokens["brand_meta"]["name"]
    p_hex = tokens["color_palette"]["primary"]["hex"]
    s_hex = tokens["color_palette"]["secondary"]["hex"]
    acc_hex = tokens["color_palette"]["accent_cta"]["hex"]

    prompts = [
        {
            "id": "facade_signage",
            "scene": "公司门头 / 建筑外立面标牌 (Outdoor Facade & Entrance Doorhead)",
            "prompt_en": f"Commercial architecture photography, modern headquarters entrance facade for '{name}', minimalist dark titanium zinc cladding wall, 3D dimensional halo-lit backlit logo sign emitting elegant brand glow ({p_hex} and warm white 4000K), tempered glass canopy, luxury polished terrazzo floor with subtle reflections, architectural lighting, dusk twilight atmosphere, ultra-realistic, architectural digest, shot on Hasselblad H6D-100c, 8k resolution, photorealistic --ar 16:9 --style raw --v 6.0",
            "prompt_zh": f"建筑摄影，'{name}' 现代化企业总部大楼门头入口外立面，极简深色钛锌板幕墙，3D金属背发光品牌标志（发光色为品牌主色 {p_hex} 搭配4000K暖白自然光），钢化玻璃雨棚，镜面水磨石地面倒影，黄昏暮色建筑照明，超高精细节，8K分辨率",
            "materials": "深灰色氟碳喷涂铝单板、304精工拉丝不锈钢字壳、进口亚克力背发光底板、防水LED模组",
            "lighting_specs": "色温 4000K 自然白光，发光均匀无暗斑，夜间照度 150-200 Lux"
        },
        {
            "id": "reception_desk",
            "scene": "前台接待区形象墙 (Corporate Reception Desk & 3D Logo Wall)",
            "prompt_en": f"Corporate interior design photography, reception lobby of '{name}', luxury Calacatta marble front desk, feature accent background wall made of fluted acoustic oak wood panels and matte slate, floating 3D brushed brass and crystal acrylic corporate logo of '{name}' with recessed warm LED perimeter backlighting ({p_hex} accents), clean ambient daylight, minimalist potted ficus bonsai, Architectural Digest interior style, raytracing, photorealistic, 8k --ar 16:9 --v 6.0",
            "prompt_zh": f"企业室内设计摄影，'{name}' 前台接待大厅，高端鱼肚白大理石前台接待桌，背景形象墙采用木质吸音格栅与哑光岩板拼接，悬浮式3D拉丝金属立体Logo标牌，内嵌柔和背光（融入品牌辅色 {acc_hex}），通透极简，8K超清画质",
            "materials": "意大利天然大理石/岩板、实木格栅吸音板、高精度金属电镀立体字、3M反光膜",
            "installation": "Logo中心水平线严格对齐人眼视觉黄金高度 1500mm，左右居中留白不小于0.5X"
        },
        {
            "id": "hallway_culture_wall",
            "scene": "走廊企业文化墙 (Office Corridor & Brand Culture Wall)",
            "prompt_en": f"Modern open office hallway corridor, corporate culture feature wall for '{name}', modular magnetic acrylic display panels showing company vision, core milestones, and global team achievements, brand primary color accents ({p_hex}), warm ceiling linear recessed spotlights, polished concrete flooring, glass conference room partitions in background, depth of field, corporate identity showcase, 8k, photorealistic --ar 16:9 --v 6.0",
            "prompt_zh": f"现代化企业走廊过道，'{name}' 企业文化展示墙，模块化亚克力与磁吸展板，展示使命愿景价值观与全球发展历程时间轴，融入品牌主题色 {p_hex} 与 {s_hex}，嵌入式线性射灯照明，自流平地面倒影，大景深，8K超清",
            "structure": "三层模块化结构：上层企业愿景Slogan（金属字），中层磁吸荣誉与里程碑，下层员工心声与团队动态"
        },
        {
            "id": "conference_room",
            "scene": "智能会议室与磨砂玻璃腰线 (Conference Room with Frosted Film & Smart Table)",
            "prompt_en": f"High-tech executive board meeting room, floor-to-ceiling smart acoustic glass partitions featuring custom frosted privacy film with translucent cut-out logo pattern of '{name}' and subtle color accent lines ({p_hex}), long walnut conference table with embedded wireless charging pads, Herman Miller ergonomic chairs, dual 85-inch teleconference displays, city skyline view outside window, corporate realism, 8k --ar 16:9 --v 6.0",
            "prompt_zh": f"高科技高管董事会议室，落地隔音玻璃隔断上贴有专属定制防撞磨砂隐私腰线，镂空展示 '{name}' 标志图案与品牌细线，胡桃木实木会议桌，人体工学椅，双85寸视频会议大屏，窗外城市天际线，8K实景渲染",
            "specs": "磨砂腰线高度 200mm，贴附中心线距离地面 1200mm，透光率 65%，上下各留 2mm 品牌色彩透明导向槽"
        },
        {
            "id": "training_room",
            "scene": "培训室与多功能厅 (Training Room & Auditorium)",
            "prompt_en": f"Tiered corporate auditorium and training lecture hall, modern stage with a minimalist wooden lectern podium branded with crisp '{name}' logo plaque, huge seamless 4K LED backdrop screen displaying presentation keynote slide in brand palette ({p_hex} and {acc_hex}), rows of comfortable theater seating with fold-out desks, professional acoustic fabric wall panels, warm stage spotlights, photorealistic, 8k --ar 16:9 --v 6.0",
            "prompt_zh": f"阶梯式企业多功能厅与培训室，现代化讲台正面嵌入 '{name}' 金属Logo标牌，无缝高清P1.2 LED大屏显示品牌16:9待机主视觉画面，专业影院级折叠桌椅，声学布艺墙面，专业舞台聚光灯，8K超清",
            "av_guideline": "LED大屏待机画面强制采用 3840x2160 分辨率，Logo位于左上角安全区，严禁强眩光纯白全屏"
        },
        {
            "id": "vip_reception_lounge",
            "scene": "贵宾接待室 (VIP Executive Reception Lounge)",
            "prompt_en": f"Luxury executive VIP lounge, soft ambient lighting, bespoke Italian leather sofa set, travertine coffee table with custom embossed leather coasters featuring subtle '{name}' debossed monogram, fine bone china tea set with gold brand rim ({acc_hex}), modern abstract wall art inspired by the brand's geometric motif, floor lamp casting warm glow, high-end private club atmosphere, 8k --ar 16:9 --v 6.0",
            "prompt_zh": f"轻奢高管贵宾接待室，柔和氛围光，意大利高级皮质沙发组合，洞石茶几上摆放印有 '{name}' 压凹微缩印记的定制真皮杯垫，骨瓷茶具配品牌金属镶边，背景悬挂基于品牌几何形态创作的现代抽象艺术画，8K实拍质感",
            "brand_integration": "弱化强商业性标牌，采用特种工艺软装微缩植入（皮具压凹、陶瓷烫金微标、纯羊毛定制地毯暗纹）"
        },
        {
            "id": "product_launch_stage",
            "scene": "全球产品发布会主舞台 (Global Product Launch Keynote Stage)",
            "prompt_en": f"Epic global product launch keynote event stage, massive 32:9 curved giant LED screen glowing with futuristic visual key visual of '{name}' in radiant electric brand colors ({p_hex}, {acc_hex}), dramatic concert-grade laser beams and atmospheric haze, glossy black reflective stage floor, charismatic presenter standing center stage holding clicker, auditorium packed with audience holding smartphones, Apple keynote level production, 8k --ar 16:9 --v 6.0",
            "prompt_zh": f"全球产品发布会主舞台巨幕，32:9 超宽环形曲面LED地屏与主屏，沉浸式动态粒子与品牌核心色彩（{p_hex} 与 {acc_hex}）交织，黑色镜面反射舞台地台，主讲人伫立光柱中央，专业发布会现场，媲美苹果与特斯拉发布会质感，8K超清",
            "key_visual_ratio": "超宽舞台主屏建议 32:9 或 21:9，中央核心主视觉安全宽度 60%，两侧留出动态光影延伸区"
        },
        {
            "id": "event_checkin_and_rollups",
            "scene": "大会签到背板与易拉宝展架 (Event Check-in Wall & Rollup Banner Zone)",
            "prompt_en": f"Grand event entrance foyer, executive check-in media wall for '{name}' summit, dark slate matte backdrop with repeating tonal monogram pattern and golden 3D metallic lettering, two premium aluminum roll-up banners standing flanking the reception table showcasing agenda and QR registration, professional photographer lighting setup, red carpet runners, commercial photography, 8k --ar 16:9 --v 6.0",
            "prompt_zh": f"发布会外场迎宾签到区，'{name}' 高峰论坛媒体签到墙，深色哑光背板饰有品牌同色系平铺底纹与立体金属字，两侧陈列极简铝合金易拉宝展架，展示大会议程与扫码注册，专业摄影灯光与红毯，8K真实感",
            "banner_specs": "展架规格 80x200cm，高精加厚哑光PVC防卷边喷绘，顶部预留 15cm Logo 视线区，底部 20cm 放置二维码与指引"
        },
        {
            "id": "stationery_flatlay",
            "scene": "企业商务办公事务用品平铺 (Corporate Stationery Suite Flatlay)",
            "prompt_en": f"Top-down flatlay photography of complete corporate stationery suite for '{name}', matte dark navy and crisp white heavy cardstock, double-sided business card with copper foil edge ({acc_hex}), A4 letterhead with subtle header logo watermark, DL envelopes with string-tie closure, vertical frosted ID badge with branded woven lanyard ({p_hex}), aluminum ballpoint pen, hardcover notebook with embossed logo, studio softbox lighting, clean shadows, 8k --ar 16:9 --v 6.0",
            "prompt_zh": f"俯拍平铺静物摄影，'{name}' 全套企业商务办公事务文具，重磅特种棉纸，双面商务名片配金属烫金滚边，A4公司信纸带浅色防伪水印，信封配复古棉线封口，垂直磨砂工牌与品牌提花挂绳，精装压凹Logo笔记本，柔光箱摄影，8K细节",
            "craft_specs": "名片选用 600g 英国新伯爵特种纸，正面双色丝网印，核心Logo部分做德国库尔兹烫金与0.3mm微压凹"
        },
        {
            "id": "app_icon_mockup",
            "scene": "移动端 App Icon 实机展示 (Mobile App Icon on Flagship Device)",
            "prompt_en": f"Product mockup shot of iPhone 16 Pro lying on minimal concrete desk, OLED Super Retina screen displaying iOS home screen, prominent custom app icon for '{name}' glowing with rich gradient ({p_hex} to {acc_hex}), clean app grid, modern workspace accessories, soft directional morning window light, shallow depth of field, photorealistic, 8k --ar 16:9 --v 6.0",
            "prompt_zh": f"旗舰手机实机界面展示，iPhone 16 Pro 放置在极简桌面上，超视网膜OLED屏幕点亮，主屏幕首排居中呈现 '{name}' App 图标，细腻色彩渐变（{p_hex} 至 {acc_hex}），逼真光影与大景深，8K超清",
            "icon_guideline": "遵循 Apple HIG 连续曲率圆角矩形，在 60pt、120pt 与 1024pt 下保持超级符号核心辨识度"
        }
    ]

    with open(output_json, "w", encoding="utf-8") as f:
        json.dump(prompts, f, indent=2, ensure_ascii=False)

    md_content = f"""# {name} · 3D 真实场景与品牌空间渲染 AI 提示词工程手册
> 基于 Midjourney v6 / FLUX.1 / Stable Diffusion XL / Gemini Imagen 3 工业级光影材质调校。

---

"""
    for idx, item in enumerate(prompts, 1):
        md_content += f"""### {idx}. {item['scene']}
- **场景标识**: `{item['id']}`
- **推荐材质与工艺**: {item.get('materials', item.get('specs', item.get('structure', item.get('craft_specs', '标准VI环保材质'))))}
- **Midjourney / FLUX 英文提示词 (一键复制)**:
```text
{item['prompt_en']}
```
- **中文语义描述**:
> {item['prompt_zh']}

---

"""

    with open(output_md, "w", encoding="utf-8") as f:
        f.write(md_content)

def generate_interactive_html(tokens, output_path):
    name = tokens["brand_meta"]["name"]
    p = tokens["color_palette"]["primary"]
    s = tokens["color_palette"]["secondary"]
    acc = tokens["color_palette"]["accent_cta"]
    light = tokens["color_palette"]["canvas_light"]
    dark = tokens["color_palette"]["surface_dark"]
    sem = tokens["color_palette"]["semantics"]

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{name} - 品牌全方位视觉识别系统 (VI Brand Identity Manual)</title>
  <link rel="stylesheet" href="tokens.css">
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: var(--font-body), var(--font-chinese);
      background-color: var(--surface-canvas);
      color: var(--text-primary);
      line-height: 1.6;
      transition: background-color 0.3s ease, color 0.3s ease;
    }}
    .container {{ max-width: 1280px; margin: 0 auto; padding: 40px 24px; }}
    
    /* Header */
    header {{
      display: flex; justify-content: space-between; align-items: center;
      padding-bottom: 24px; border-bottom: 1px solid var(--surface-border); margin-bottom: 40px;
    }}
    .brand-title h1 {{ font-size: 32px; font-weight: 800; color: var(--brand-primary); }}
    .brand-title p {{ font-size: 14px; color: var(--text-secondary); margin-top: 4px; }}
    .theme-toggle {{
      background: var(--surface-card); border: 1px solid var(--surface-border);
      color: var(--text-primary); padding: 8px 16px; border-radius: var(--radius-full);
      cursor: pointer; font-size: 14px; font-weight: 600;
    }}

    /* Section Styles */
    section {{ margin-bottom: 56px; }}
    .section-header {{ margin-bottom: 24px; }}
    .section-header h2 {{ font-size: 24px; font-weight: 700; display: flex; align-items: center; gap: 10px; }}
    .section-header h2::before {{
      content: ""; display: inline-block; width: 6px; height: 24px;
      background: var(--brand-primary); border-radius: 3px;
    }}
    .section-header p {{ font-size: 14px; color: var(--text-secondary); margin-top: 4px; }}

    /* Cards & Grids */
    .grid-4 {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 20px; }}
    .grid-3 {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 24px; }}
    .grid-2 {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(440px, 1fr)); gap: 24px; }}
    .card {{
      background: var(--surface-card); border: 1px solid var(--surface-border);
      border-radius: var(--radius-md); padding: 24px; box-shadow: var(--shadow-sm);
    }}

    /* Color Swatches */
    .color-preview {{ height: 110px; border-radius: var(--radius-sm); margin-bottom: 14px; border: 1px solid rgba(0,0,0,0.06); }}
    .color-info h3 {{ font-size: 16px; font-weight: 700; margin-bottom: 6px; }}
    .color-meta {{ font-size: 13px; color: var(--text-secondary); font-family: var(--font-mono); }}
    .color-copy-pill {{
      display: inline-block; background: rgba(0,0,0,0.04); padding: 2px 8px;
      border-radius: 4px; cursor: pointer; margin-top: 6px; font-size: 12px;
    }}

    /* Components Showcase */
    .btn {{
      display: inline-flex; align-items: center; justify-content: center;
      padding: 10px 22px; border-radius: var(--radius-md); font-weight: 600;
      cursor: pointer; text-decoration: none; transition: all 0.2s; border: none; font-size: 14px;
    }}
    .btn-primary {{ background: var(--brand-primary); color: #FFF; box-shadow: var(--shadow-glow); }}
    .btn-secondary {{ background: var(--brand-secondary); color: #FFF; }}
    .btn-accent {{ background: var(--brand-accent); color: #0F172A; }}
    .btn-outline {{ background: transparent; border: 1.5px solid var(--brand-primary); color: var(--brand-primary); }}

    /* SVG Previews */
    .preview-box {{
      background: #F1F5F9; border-radius: var(--radius-md); padding: 20px;
      text-align: center; border: 1px dashed var(--surface-border); margin-top: 12px;
    }}
    .preview-box img, .preview-box svg {{ max-width: 100%; height: auto; border-radius: 6px; box-shadow: var(--shadow-sm); }}

    /* Prompt Box */
    .prompt-box {{
      background: #020617; color: #E2E8F0; padding: 16px; border-radius: var(--radius-sm);
      font-family: var(--font-mono); font-size: 12px; line-height: 1.5; max-height: 140px;
      overflow-y: auto; position: relative; margin-top: 10px;
    }}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div class="brand-title">
        <h1>{name}</h1>
        <p>企业全方位品牌视觉识别系统规范手册 · 企业版 v2.0</p>
      </div>
      <button class="theme-toggle" onclick="toggleTheme()">🌓 切换明暗视图</button>
    </header>

    <!-- 1. 基础核心色彩系统 -->
    <section>
      <div class="section-header">
        <h2>01 / 品牌核心色彩系统 (Color DNA &amp; Ratios)</h2>
        <p>严格遵循 60-30-10 黄金色彩配比法则，并通过 WCAG 2.1 AA/AAA 国际可访问性无障碍认证。</p>
      </div>
      <div class="grid-4">
        <div class="card">
          <div class="color-preview" style="background-color: {p['hex']};"></div>
          <div class="color-info">
            <h3>{p['name']}</h3>
            <p class="color-meta">HEX: {p['hex']}<br>RGB: {p['rgb']}<br>CMYK: {p['cmyk']}</p>
            <span class="color-copy-pill" onclick="copyText('{p['hex']}')">📋 复制色值</span>
          </div>
        </div>
        <div class="card">
          <div class="color-preview" style="background-color: {s['hex']};"></div>
          <div class="color-info">
            <h3>{s['name']}</h3>
            <p class="color-meta">HEX: {s['hex']}<br>RGB: {s['rgb']}<br>CMYK: {s['cmyk']}</p>
            <span class="color-copy-pill" onclick="copyText('{s['hex']}')">📋 复制色值</span>
          </div>
        </div>
        <div class="card">
          <div class="color-preview" style="background-color: {acc['hex']};"></div>
          <div class="color-info">
            <h3>{acc['name']}</h3>
            <p class="color-meta">HEX: {acc['hex']}<br>RGB: {acc['rgb']}<br>CMYK: {acc['cmyk']}</p>
            <span class="color-copy-pill" onclick="copyText('{acc['hex']}')">📋 复制色值</span>
          </div>
        </div>
        <div class="card">
          <div class="color-preview" style="background-color: {dark['hex']};"></div>
          <div class="color-info">
            <h3>{dark['name']}</h3>
            <p class="color-meta">HEX: {dark['hex']}<br>RGB: {dark['rgb']}<br>用途: 文字主色 / 暗色底板</p>
            <span class="color-copy-pill" onclick="copyText('{dark['hex']}')">📋 复制色值</span>
          </div>
        </div>
      </div>
    </section>

    <!-- 2. 线上数字应用系统 -->
    <section>
      <div class="section-header">
        <h2>02 / 线上数字应用系统 (Digital Application Suite)</h2>
        <p>覆盖 Web UI 组件、App Icon 矩阵、多端 Favicon 与 16:9 PPT 母版规范。</p>
      </div>
      <div class="grid-2">
        <div class="card">
          <h3>Web UI 标准设计规范与交互态</h3>
          <p style="font-size:14px; color:var(--text-secondary); margin: 8px 0 16px;">基于 tokens.css 驱动的标准组件，支持一键切换主题与无障碍交互。</p>
          <div style="display:flex; gap:12px; flex-wrap:wrap; margin-bottom: 20px;">
            <button class="btn btn-primary">Primary 核心操作</button>
            <button class="btn btn-secondary">Secondary 次级操作</button>
            <button class="btn btn-accent">Accent 转化锚点</button>
            <button class="btn btn-outline">Outline 描边边框</button>
          </div>
          <div class="prompt-box">
            /* Web Tokens 导入说明 */<br>
            @import url("tokens.css");<br>
            background: var(--brand-primary);<br>
            box-shadow: var(--shadow-glow);
          </div>
        </div>

        <div class="card">
          <h3>移动端 App Icon 与 Favicon 矩阵</h3>
          <p style="font-size:14px; color:var(--text-secondary); margin: 8px 0 16px;">支持 iOS 1024 连续曲率、Android 自适应双层与 Web 多尺寸 Favicon。</p>
          <div class="preview-box" style="display:flex; justify-content:center; gap:24px; align-items:center;">
            <img src="svg/ios_app_icon_1024.svg" width="96" height="96" style="border-radius:22px;" alt="iOS Icon">
            <img src="svg/favicon.svg" width="48" height="48" alt="Favicon">
          </div>
        </div>
      </div>
    </section>

    <!-- 3. 线下与实体空间应用系统 -->
    <section>
      <div class="section-header">
        <h2>03 / 线下实体空间与环境导视系统 (Environmental Suite)</h2>
        <p>含公司门头、前台形象、文化墙、会议室磨砂腰线、培训室大屏、发布会舞台巨幕与商务文具。</p>
      </div>
      <div class="grid-2">
        <div class="card">
          <h3>商务办公事务文具 (名片、工牌与展架)</h3>
          <p style="font-size:14px; color:var(--text-secondary); margin: 8px 0 16px;">标准 90x54mm 双面名片与 54x85mm CR80 工牌矢量预览：</p>
          <div class="preview-box">
            <img src="svg/business_card_front.svg" style="max-height:160px; margin-right:12px;" alt="Card Front">
            <img src="svg/business_card_back.svg" style="max-height:160px;" alt="Card Back">
          </div>
        </div>

        <div class="card">
          <h3>会议室磨砂玻璃防撞腰线</h3>
          <p style="font-size:14px; color:var(--text-secondary); margin: 8px 0 16px;">透光率 65%，高度 200mm，中心距地 1200mm：</p>
          <div class="preview-box">
            <img src="svg/meeting_room_frosted_film.svg" style="width:100%; max-height:80px;" alt="Frosted Film">
          </div>
        </div>
      </div>
    </section>

    <!-- 4. 3D 真实场景 AI 渲染 Prompts 指南 -->
    <section>
      <div class="section-header">
        <h2>04 / 3D 真实场景 AI 渲染提示词工程 (Midjourney &amp; FLUX Prompts)</h2>
        <p>10 大核心场景全覆盖，可直接复制至 Midjourney v6 / FLUX.1 生成出版级空间效果图。</p>
      </div>
      <div class="grid-2">
        <div class="card">
          <h3>🏢 公司门头与建筑外立面 (Outdoor Facade)</h3>
          <p style="font-size:13px; color:var(--text-secondary); margin-top:4px;">材质：深色钛锌板幕墙 + 3D金属背发光（色温4000K自然白）</p>
          <div class="prompt-box" id="p1">Commercial architecture photography, modern headquarters entrance facade for '{name}', minimalist dark titanium zinc cladding wall, 3D dimensional halo-lit backlit logo sign emitting elegant brand glow ({p['hex']} and warm white 4000K), tempered glass canopy, luxury polished terrazzo floor with subtle reflections, architectural lighting, dusk twilight atmosphere, ultra-realistic, architectural digest, shot on Hasselblad H6D-100c, 8k resolution, photorealistic --ar 16:9 --style raw --v 6.0</div>
          <button class="btn btn-outline" style="margin-top:10px; padding:6px 14px; font-size:12px;" onclick="copyPrompt('p1')">📋 复制门头 Prompt</button>
        </div>

        <div class="card">
          <h3>🎤 全球产品发布会主舞台巨幕 (Keynote Stage KV)</h3>
          <p style="font-size:13px; color:var(--text-secondary); margin-top:4px;">规格：32:9 超宽环形曲面LED地屏与主屏 + 激光矩阵</p>
          <div class="prompt-box" id="p2">Epic global product launch keynote event stage, massive 32:9 curved giant LED screen glowing with futuristic visual key visual of '{name}' in radiant electric brand colors ({p['hex']}, {acc['hex']}), dramatic concert-grade laser beams and atmospheric haze, glossy black reflective stage floor, charismatic presenter standing center stage holding clicker, auditorium packed with audience, Apple keynote level production, 8k --ar 16:9 --v 6.0</div>
          <button class="btn btn-outline" style="margin-top:10px; padding:6px 14px; font-size:12px;" onclick="copyPrompt('p2')">📋 复制发布会 Prompt</button>
        </div>
      </div>
    </section>

    <footer style="margin-top: 60px; padding-top: 24px; border-top: 1px solid var(--surface-border); text-align: center; font-size: 13px; color: var(--text-muted);">
      © 2026 {name}. 本品牌视觉识别系统受著作权与商标法全域保护 · 由 Brand Visual System Master 自动生成
    </footer>
  </div>

  <script>
    function toggleTheme() {{
      const current = document.documentElement.getAttribute('data-theme');
      if (current === 'dark') {{
        document.documentElement.removeAttribute('data-theme');
      }} else {{
        document.documentElement.setAttribute('data-theme', 'dark');
      }}
    }}
    function copyText(val) {{
      navigator.clipboard.writeText(val);
      alert('已复制色值到剪贴板: ' + val);
    }}
    function copyPrompt(id) {{
      const txt = document.getElementById(id).innerText;
      navigator.clipboard.writeText(txt);
      alert('已复制 AI 渲染提示词到剪贴板！可以直接在 Midjourney / FLUX 中粘贴生成。');
    }}
  </script>
</body>
</html>
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

def run_master_pipeline(logo_input, brand_name, output_dir):
    print("==================================================================")
    print(f"🚀 Brand Visual System Master: Generating Full Identity System")
    print(f"   - Brand Name: {brand_name}")
    print(f"   - Input: {logo_input}")
    print(f"   - Output Directory: {output_dir}")
    print("==================================================================")

    os.makedirs(output_dir, exist_ok=True)
    svg_dir = os.path.join(output_dir, "svg")
    prompts_dir = os.path.join(output_dir, "prompts")
    os.makedirs(svg_dir, exist_ok=True)
    os.makedirs(prompts_dir, exist_ok=True)

    # 1. Extraction / Tokenization
    tokens_path = os.path.join(output_dir, "brand_tokens.json")
    if logo_input and logo_input.endswith(".json") and os.path.exists(logo_input):
        print("[*] Loading existing brand tokens from JSON...")
        with open(logo_input, "r", encoding="utf-8") as f:
            tokens = json.load(f)
    else:
        print("[*] Extracting visual DNA from logo...")
        tokens = build_brand_tokens(logo_input, brand_name)

    with open(tokens_path, "w", encoding="utf-8") as f:
        json.dump(tokens, f, indent=2, ensure_ascii=False)
    if logo_input and os.path.exists(logo_input) and not logo_input.endswith(".json"):
        shutil.copy2(logo_input, os.path.join(output_dir, "logo_source" + os.path.splitext(logo_input)[1]))
    print(f"[✓] Step 1/6: Saved brand tokens -> {tokens_path}")

    # 2. CSS Design Tokens
    css_path = os.path.join(output_dir, "tokens.css")
    generate_css_tokens(tokens, css_path)
    print(f"[✓] Step 2/6: Generated CSS design tokens -> {css_path}")

    # 3. Physical Stationery & Signage SVGs
    generate_all_stationery(tokens, svg_dir)
    print(f"[✓] Step 3/6: Generated physical stationery & signage SVGs -> {svg_dir}")

    # 4. Digital App Icons & Favicon
    generate_all_icons(tokens, svg_dir)
    print(f"[✓] Step 4/6: Generated App icon suite -> {svg_dir}")

    # 5. 3D Photorealistic AI Prompts (10 Scenes)
    prompts_json = os.path.join(prompts_dir, "photorealistic_vi_prompts.json")
    prompts_md = os.path.join(prompts_dir, "photorealistic_vi_prompts.md")
    generate_photorealistic_prompts(tokens, prompts_json, prompts_md)
    print(f"[✓] Step 5/6: Generated 3D spatial AI prompts -> {prompts_md}")

    # 6. Interactive HTML Guidelines Manual
    guidelines_html = os.path.join(output_dir, "brand_guidelines.html")
    generate_interactive_html(tokens, guidelines_html)
    print(f"[✓] Step 6/6: Rendered interactive VI Guidelines manual -> {guidelines_html}")

    print("==================================================================")
    print("✨ Full Brand Visual Identity System Successfully Generated!")
    print(f"👉 Open {guidelines_html} in your browser to inspect.")
    print("==================================================================")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 generate_vi_system.py <logo_image_or_json> [brand_name] [output_dir]")
        sys.exit(1)
        
    logo_file = sys.argv[1]
    name = sys.argv[2] if len(sys.argv) > 2 else "RenAsset & RenWork Enterprise"
    out = sys.argv[3] if len(sys.argv) > 3 else "dist_brand_vi"
    
    run_master_pipeline(logo_file, name, out)
